backend:
  name: github
  repo: harputnik2/mattermotion
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages"
    files:
      - file: "src/content/home.md"
        label: "home page"
        name: "home"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
      - file: "src/content/pricing.md"
        label: "pricing page"
        name: "pricing"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/pricing"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
  - name: "projects"
    label: "projects"
    files:
      - file: "src/content/projects/virtualtours.md"
        label: "virtual tours"
        name: "virtualtours"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/projects/virtualtours"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "virtualtours"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
      - file: "src/content/projects/animations.md"
        label: "animations"
        name: "animations"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/projects/animations"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "animations"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
          - {label: "Animation", name: "animation", widget: list, fields: [
              {label: "Video", name: "video", widget: "file"},
              {label: "Description", name: "description", widget: "text"}
            ]}
      - file: "src/content/projects/visualizations.md"
        label: "visualizations"
        name: "visualizations"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/projects/visualizations"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "visualizations"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
          - {label: "Visualization", name: "visualization", widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"}
            ]}
