backend:
  name: github
  repo: harputnik2/mattermotion
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/media
public_folder: /img

collections:
  - name: visualizations
    label: Visualizations
    folder: "src/content/visualizations"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "visualization"}
      - {name: path, label: Path, widget: string, hint: "template path: /visualizations/visualization_name"}
      - {name: year, label: Year, widget: string}
      - {name: title, label: Title}
      - {name: description, label: Description, widget: string}
      - {name: minature, label: "Artwork Minature", widget: "image"}
      - {label: "Visualizations", name: "visualizations", widget: list, fields: [
        {label: "Image", name: "image", widget: "image"}
      ]}
  - name: animations
    label: Animations
    folder: "src/content/animations"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "animation"}
      - {name: path, label: Path, widget: string, hint: "template path: /animations/animation_name"}
      - {name: year, label: Year, widget: string}
      - {name: title, label: Title}
      - {name: description, label: Description, widget: string}
      - {name: minature, label: "Artwork Minature", widget: "image"}
      - {label: "Animation", name: "animation", widget: file}
  - name: virtualtours
    label: "Virtual Tours"
    folder: "src/content/virtualtours"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "virtualtour"}
      - {name: path, label: Path, widget: string, hint: "template path: /virtualtours/virtualtour_name"}
      - {name: year, label: Year, widget: string}
      - {name: title, label: Title}
      - {name: description, label: Description, widget: string}
      - {name: minature, label: "Artwork Minature", widget: "image"}
      - {name: "virtualtour", label: "Virtual Tour Path", widget: string}
  - name: "homepage"
    label: "Home Page"
    files:
      - file: "src/content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Hero", name: "hero", widget: "object", collapsed: true, fields: [
            {label: "Main Headline", name: "mainHeadline", widget: "string"},
            {label: "Motto", name: "motto", widget: "string"}
          ]}
          - {label: "About", name: "about", widget: "object", collapsed: true, fields: [
            {label: "Title", name: "title", widget: "string"},
            {label: "Content", name: "content", widget: "markdown"}
          ]}
          - {label: "What We Do", name: "categories", widget: "object", collapsed: true, fields: [
            {label: "Animations", name: "animations", widget: "object", fields: [
              {label: "Animation Minature", name: "minature", widget: "image"},
              {label: "Teaser", name: "teaser", widget: "string"}
            ]},
            {label: "Virtual Tours", name: "virtualtours", widget: "object", fields: [
              {label: "Virtual Tour Minature", name: "minature", widget: "image"},
              {label: "Teaser", name: "teaser", widget: "string"}
            ]},
            {label: "Visualizations", name: "visualizations", widget: "object", collapsed: false, fields: [
              {label: "Visualizations Minature", name: "minature", widget: "object", fields: [
                {label: "Image 1", name: "image1", widget: "image"},
                {label: "Image 2", name: "image2", widget: "image"},
                {label: "Image 3", name: "image3", widget: "image"}
              ]},
              {label: "Teaser", name: "teaser", widget: "string"}
            ]},
          ]}
          - {label: "What others say", name: "whatotherssay", collapsed: false, widget: "list", fields: [
            {label: "Logo", name: "logo", widget: "image"},
            {label: "Content", name: "content", widget: "string"},
            {label: "Author", name: "author", widget: "string"}
          ]}
  - name: "pricingpage"
    label: "Pricing Page"
    files:
      - file: "src/content/pricing.md"
        label: "Pricing Page"
        name: "pricing"
        fields:
          - {label: "Path", name: "path", widget: string, default: "/pricing"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
