export * from './androidChrome192x192.png'
export * from './androidChrome512x512.png'
export * from './appleTouchIcon.png'
export * from './favicon16x16.png'
export * from './favicon32x32.png'
export * from './favicon.ico'
export * from './mstile150x150.png'
export * from './safariPinnedTab.svg'
